namespace: myapp

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

gateway:
  enabled: true
  gatewayClassName: nginx
  hostname: abc.example.com
  tls:
    enabled: true
    secretName: myapp-tls

ingress:
  enabled: false
